language: node_js

node_js:
    - "4.3"
  
install:
    - npm install

env:
  global:
    - secure: hGYNzB1NM7Z8RF32bTUDUEPlU6DQHtqG9zEUJpWVK/AskIug7YZJovC6nA4UTe6DJdEh+S/IdHHmrO6HG8DMMVcgClAEkNyyUCcSBK+2uPxNfmXwLIxsolK0fiZ0yGCZm6M6Xnorsd3zMqjlkbRlO7tSQlVQtNCR/CZ6Gsyw4gJ7KGOKnFm3k74dnjdhJdA6bbZXU+QdE1Zac5oRkcwGcJwtnkS8fG4V3hYxNy8YSUzYK1jNMYArJKZQLvKqyWsqbaIPDEARGvECSUcxQ0gepyiuFMpw9MLnuGx228Spr0i56L1zk/txsX+PLFz4tsMqXMaNWpDKEDsLeyJ2F+8ZyJ4wkHsrYOoC2d72wJvZnirhSuS0rE4IG4/GerL9DGzXLDLk7sPfDp3/lsN95U9/KdCrXTq4gtowqwbPoINQ/PwdMqq6+5KCKgIIGkd5rEjes+zwJYogIpx/ioohdeTKJtEmBqSTl5+cutXIOhgWOnWT+KKn8T8biGHPc64JGxoPBPsIysI3n5nmiKR5thKSEqyWOgttM8Ng6buNIKRfe27e7m0dX/GyZOmzTQRWBwHh4+JZ1nYAo9JqqCbmTx+21L9xBMk1v6vndTF0XvPYBCJPGKS0Z5Uf4bk4SHVOH0TaKQxab13/vPvBUiewhKCHFe7wpGSRfNESewXSimjuI2E=
    - secure: KhxTYuVOqaVn6+Ij8QF8WuMBLR5xJ52xEyMHa85V0xnqhGPeLu36gbU9sUk4i6Na47y3ITgW7LBlB09OfhmmI1TImcgtQWwtcsWTy+YCOEfhdpuEh8kW+ruWcAo2u1L+/klYrJ8f5I74P2P2l25N3tgq00bzwQPyrKQOqld0gr/NUiaGTDg9RFzykrXB+JS2r65p5MGtrLkdz63nDpv0cecunnSD7zYrLOK8rJcYvR33mUF2OfFnJXev4rx6zy/smcmoa/F7IxG/OUQ+32pjTfG8Ckj5JpjQjDU00NX2tLRZv3/gezpASLinZx7srNsD9UjzK4T/z7wsTHN/JOvsro7AKc53/S+A2+Vqjx4uHzhMZzbt1O+VzdQasxiu2qHbnISn9e7J5woiGXEGni3GsUkVigNI3AelvmSMCsBvAFdaAPCN7dOwYQ2ncwXTOmA/mfEq6fmrfgwGz6ji7BurpQEnZTtEMadL7iBzFSFng4FHLS3Olo0G2+EIJF9P0Vcvu3QFmmavOBNtLxLB3MwsOj7ZcKazpHW99wKvY0XRp0VFz17bFgmbzvQu7fXS0XU19nL57xZ/PgWd1nelQOMx0RuRrRoKjBlohlu5u4Sfnp8Xdhu48UB1qpZl6qjpFyAULzYWIpWoMQxZV7bYqBh0U2/+uvV+CIX5oY0dYRYeabA=

script:
    - npm test  
    

